name: dish
description: SNS specialized for restaurants

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0

  intl: ^0.17.0
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  wechat_camera_picker: ^2.4.0
  wechat_assets_picker: ^6.0.6
  image_cropper: ^1.4.1
  google_maps_flutter: ^2.0.8
  geolocator: ^7.6.0
  firebase_core: ^1.6.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^3.1.1
  google_sign_in: ^5.0.0
  flutter_facebook_auth: "^3.5.0"
  # flutter_facebook_login: ^3.0.0
  # cloud_firestore: ^0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
